const phraseBanks = {

  idle: [
    "AWAITING SUBJECT",
    "GAYDAR PROTOCOL ACTIVE",
    "SYSTEM READY",
    "SCANNING FOR SUBJECTS",
    "STANDBY",
  ],

  scanning: [
    "INITIALISING GAYDAR PROTOCOL",
    "SCANNING SUBJECT",
    "ANALYSING MANNERISMS",
    "CROSS-REFERENCING DATABASE",
    "RUNNING ORIENTATION ALGORITHM",
    "MEASURING CHARISMA LEVELS",
    "ANALYSING CULTURAL SIGNALS",
    "DETECTING FASHION COEFFICIENTS",
    "PROCESSING BEHAVIOURAL DATA",
    "RESULT IMMINENT",
  ],

  straight: [
    "ORIENTATION: HETEROSEXUAL",
    "CLASSIFICATION: HETEROSEXUAL",
    "SUBJECT: HETEROSEXUAL",
    "READING: HETEROSEXUAL",
  ],

  straightSub: [
    "NO FURTHER ACTION REQUIRED",
    "SUBJECT CLEARED",
    "PROCEED WITHOUT INCIDENT",
    "STANDARD ORIENTATION CONFIRMED",
    "THREAT LEVEL: ZERO",
    "HETERONORMATIVITY: INTACT",
    "BORING. NEXT SUBJECT.",
  ],

  alarm: [
    "ALERT: HOMOSEXUAL DETECTED",
    "WARNING: NON-HETERONORMATIVE SUBJECT",
    "ALERT: PRIDE SIGNAL CONFIRMED",
    "SYSTEM ALERT: HOMOSEXUAL",
  ],

  alarmSub: [
    "THREAT LEVEL: RAINBOW",
    "PRIDE LEVELS: CRITICAL",
    "UNAUTHORIZED FABULOUSNESS DETECTED",
    "GAY AGENDA: CONFIRMED",
    "INITIATING RAINBOW PROTOCOL",
    "ALERT AUTHORITIES",
    "EXCESS CHARISMA: EXTREME",
    "EMERGENCY DISCO RESPONSE REQUIRED",
    "NON-NORMATIVE ORIENTATION VERIFIED",
    "CODE RAINBOW",
    "FABULOUSNESS: MAXIMUM",
    "CULTURAL THREAT LEVEL: FABULOUS",
  ],

};

function getRandomPhrase(bank) {
  const arr = phraseBanks[bank];
  if (!arr || arr.length === 0) return "";
  return arr[Math.floor(Math.random() * arr.length)];
}
