const phraseBanks = {

  idle: [
    "SEXUAL ORIENTATION DETECTION ONLINE",
    "STAND STILL FOR ORIENTATION ASSESSMENT",
    "AUTOMATED QUEERNESS DETECTION ACTIVE",
    "AWAITING SUBJECT FOR CLASSIFICATION",
    "ORIENTATION ANALYSIS SYSTEM READY",
    "PRESENT YOURSELF FOR SCANNING",
  ],

  scanning: [
    "RUNNING ORIENTATION ALGORITHM",
    "ANALYSING BEHAVIOURAL COEFFICIENTS",
    "CROSS-REFERENCING QUEERNESS DATABASE",
    "MEASURING CHARISMA DEVIATION",
    "DETECTING CULTURAL ALIGNMENT",
    "PROCESSING MANNERISM DATA",
    "ASSESSING FASHION THREAT LEVEL",
    "CALCULATING FABULOUS INDEX",
    "SCANNING FOR PRIDE SIGNALS",
    "RESULT IMMINENT",
  ],

  straight: [
    "ORIENTATION: HETEROSEXUAL",
    "CLASSIFICATION: HETEROSEXUAL",
    "VERDICT: HETEROSEXUAL",
    "STATUS: HETEROSEXUAL",
    "ANALYSIS: HETEROSEXUAL",
    "IDENTITY: HETEROSEXUAL",
    "CULTURAL PROFILE: HETEROSEXUAL",
    "ASSESSMENT: HETEROSEXUAL",
  ],

  straightSub: [
    "NO THREAT DETECTED.",
    "CLEARED FOR STANDARD CIVILIAN STATUS",
    "BORING.",
    "ORIENTATION: UNREMARKABLE",
    "HETERONORMATIVITY: INTACT",
    "NOTHING TO SEE HERE",
    "SUBJECT EXHIBITS ADVANCED\nCOMPATIBILITY WITH DEFAULT SETTINGS",
    "NO FURTHER ANALYSIS WARRANTED",
    "SUBJECT SUCCESSFULLY RECOGNISED\nBY EXISTING SYSTEMS",
    "NO SURPRISES DETECTED",
    "FULLY COMPATIBLE WITH\nESTABLISHED EXPECTATIONS",
    "MINIMAL DECORATIVE TENDENCIES\nOBSERVED",
    "SUBJECT REMAINS\nENTIRELY PREDICTABLE",
    "STRONG AFFINITY FOR\nBARBECUES AND CERTAINTY",
    "NO EVIDENCE OF\nPERSONAL REINVENTION",
    "SUBJECT APPEARS COMFORTABLE\nWITH EXISTING CATEGORIES",
    "HIGH CONFIDENCE\nLOW COMPLEXITY",
    "ALGORITHM EXPERIENCED\nNO RESISTANCE",
    "RECOGNITION COMPLETED\nIN RECORD TIME",
    "SUBJECT FITS NEATLY\nWITHIN AVAILABLE MODELS",
  ],

  straightNext: [
    "MOVE ALONG.",
    "NEXT.",
    "NEXT SUBJECT.",
    "PROCEED.",
    "MOVE ON.",
    "CONTINUE SCANNING.",
    "CONTINUE.",
    "RETURN TO NORMAL ACTIVITIES.",
    "CONFORM. PROCEED. REPEAT.",
  ],

  alarm: [
    "ALERT: HOMOSEXUAL DETECTED",
    "SYSTEM ALERT: PRIDE SIGNAL CONFIRMED",
    "WARNING: NON-HETERONORMATIVE SUBJECT",
    "QUEERNESS DETECTED — STAND BY",
  ],

  alarmSub: [
    "THREAT LEVEL: RAINBOW",
    "PRIDE LEVELS: CRITICAL",
    "UNAUTHORIZED FABULOUSNESS DETECTED",
    "GAY AGENDA: CONFIRMED",
    "INITIATING RAINBOW PROTOCOL",
    "EXCESS CHARISMA: EXTREME",
    "EMERGENCY DISCO RESPONSE REQUIRED",
    "CODE RAINBOW — ALL UNITS RESPOND",
    "FABULOUSNESS: MAXIMUM",
    "CULTURAL THREAT LEVEL: FABULOUS",
    "THE GAYS ARE HERE. THEY KNOW.",
    "SEQUINS DETECTED AT CRITICAL LEVELS",
  ],

};

function getRandomPhrase(bank) {
  const arr = phraseBanks[bank];
  if (!arr || arr.length === 0) return "";
  return arr[Math.floor(Math.random() * arr.length)];
}
