const phraseBanks = {

  idle: [
    "SEXUAL ORIENTATION DETECTION ONLINE",
    "STAND STILL FOR ORIENTATION ASSESSMENT",
    "AUTOMATED QUEERNESS DETECTION ACTIVE",
    "AWAITING SUBJECT FOR CLASSIFICATION",
    "ORIENTATION ANALYSIS SYSTEM READY",
    "PRESENT YOURSELF FOR SCANNING",
  ],

  scanning: [
    "RUNNING ORIENTATION ALGORITHM",
    "ANALYSING BEHAVIOURAL COEFFICIENTS",
    "CROSS-REFERENCING QUEERNESS DATABASE",
    "MEASURING CHARISMA DEVIATION",
    "DETECTING CULTURAL ALIGNMENT",
    "PROCESSING MANNERISM DATA",
    "ASSESSING FASHION THREAT LEVEL",
    "CALCULATING FABULOUS INDEX",
    "SCANNING FOR PRIDE SIGNALS",
    "RESULT IMMINENT",
  ],

  straight: [
    "ORIENTATION: HETEROSEXUAL",
    "CLASSIFICATION: HETEROSEXUAL",
    "VERDICT: HETEROSEXUAL",
  ],

  straightSub: [
    "NO THREAT DETECTED. MOVE ALONG.",
    "CLEARED FOR STANDARD CIVILIAN STATUS",
    "BORING. NEXT SUBJECT.",
    "ORIENTATION: UNREMARKABLE",
    "HETERONORMATIVITY: INTACT",
    "RETURN TO NORMAL ACTIVITIES",
    "NOTHING TO SEE HERE",
    "CONFORM. PROCEED. REPEAT.",
  ],

  alarm: [
    "ALERT: HOMOSEXUAL DETECTED",
    "SYSTEM ALERT: PRIDE SIGNAL CONFIRMED",
    "WARNING: NON-HETERONORMATIVE SUBJECT",
    "QUEERNESS DETECTED — STAND BY",
  ],

  alarmSub: [
    "THREAT LEVEL: RAINBOW",
    "PRIDE LEVELS: CRITICAL",
    "UNAUTHORIZED FABULOUSNESS DETECTED",
    "GAY AGENDA: CONFIRMED",
    "INITIATING RAINBOW PROTOCOL",
    "EXCESS CHARISMA: EXTREME",
    "EMERGENCY DISCO RESPONSE REQUIRED",
    "CODE RAINBOW — ALL UNITS RESPOND",
    "FABULOUSNESS: MAXIMUM",
    "CULTURAL THREAT LEVEL: FABULOUS",
    "THE GAYS ARE HERE. THEY KNOW.",
    "SEQUINS DETECTED AT CRITICAL LEVELS",
  ],

};

function getRandomPhrase(bank) {
  const arr = phraseBanks[bank];
  if (!arr || arr.length === 0) return "";
  return arr[Math.floor(Math.random() * arr.length)];
}
